/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 *
 * @author irsal lazuard
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    ImageIcon logoImg = new ImageIcon("logo.png");

    CardLayout cardLayout;

    public Home() {
        initComponents();

        Component[] components = this.getContentPane().getComponents();
        for (Component component : components) {
            if (component instanceof JButton) {
                ((JButton) component).setUI(new BasicButtonUI());
                ((JButton) component).setFocusPainted(false);
            }
        }

        cardLayout = (CardLayout) (panelPages.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        Sidebar = new javax.swing.JPanel();
        btnLogo = new javax.swing.JButton();
        btnTambahBarang = new javax.swing.JButton();
        btnLaporBarang = new javax.swing.JButton();
        btnStok = new javax.swing.JButton();
        btnKaryawan = new javax.swing.JButton();
        btnSuplier = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        panelPages = new javax.swing.JPanel();
        tambahBarangPage = new javax.swing.JPanel();
        header = new javax.swing.JDesktopPane();
        title = new javax.swing.JLabel();
        labelKodeBarang = new javax.swing.JLabel();
        inputKBarang = new javax.swing.JTextField();
        inputNBarang = new javax.swing.JTextField();
        labelNamaBarang = new javax.swing.JLabel();
        inputSuplier = new javax.swing.JTextField();
        labelSuplier = new javax.swing.JLabel();
        labelJumlah = new javax.swing.JLabel();
        inputJumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        labelKodeBarangEdit = new javax.swing.JLabel();
        labelNamaBarangEdit = new javax.swing.JLabel();
        labelSuplierEdit = new javax.swing.JLabel();
        labelJumlahEdit = new javax.swing.JLabel();
        inputJumlahEdit = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        cbKdBarang = new javax.swing.JComboBox<>();
        cbNmBarang = new javax.swing.JComboBox<>();
        cbSuplier = new javax.swing.JComboBox<>();
        laporBarangPage = new javax.swing.JPanel();
        stokPage = new javax.swing.JPanel();
        header2 = new javax.swing.JDesktopPane();
        title2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnSimpan2 = new javax.swing.JButton();
        inputJumlahEdit2 = new javax.swing.JTextField();
        karyawanPage = new javax.swing.JPanel();
        suplierPage = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setPreferredSize(new java.awt.Dimension(960, 684));

        Sidebar.setBackground(new java.awt.Color(153, 153, 153));
        Sidebar.setMaximumSize(new java.awt.Dimension(190, 64));
        Sidebar.setMinimumSize(new java.awt.Dimension(190, 64));
        Sidebar.setPreferredSize(new java.awt.Dimension(190, 59));
        Sidebar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        btnLogo.setBackground(new java.awt.Color(38, 38, 38));
        btnLogo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnLogo.setForeground(new java.awt.Color(255, 255, 255));
        btnLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N
        btnLogo.setToolTipText("");
        btnLogo.setFocusable(false);
        btnLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogo.setMaximumSize(new java.awt.Dimension(177, 39));
        btnLogo.setMinimumSize(new java.awt.Dimension(177, 39));
        btnLogo.setPreferredSize(new java.awt.Dimension(190, 100));
        btnLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoActionPerformed(evt);
            }
        });
        Sidebar.add(btnLogo);

        btnTambahBarang.setBackground(new java.awt.Color(0, 0, 0));
        btnTambahBarang.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnTambahBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default.png"))); // NOI18N
        btnTambahBarang.setText("Tambah Barang");
        btnTambahBarang.setToolTipText("");
        btnTambahBarang.setFocusable(false);
        btnTambahBarang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTambahBarang.setMaximumSize(new java.awt.Dimension(177, 39));
        btnTambahBarang.setMinimumSize(new java.awt.Dimension(177, 39));
        btnTambahBarang.setPreferredSize(new java.awt.Dimension(177, 39));
        btnTambahBarang.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/hover.png"))); // NOI18N
        btnTambahBarang.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/active.png"))); // NOI18N
        btnTambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahBarangActionPerformed(evt);
            }
        });
        Sidebar.add(btnTambahBarang);

        btnLaporBarang.setBackground(new java.awt.Color(0, 0, 0));
        btnLaporBarang.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnLaporBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default.png"))); // NOI18N
        btnLaporBarang.setText("Laporkan Barang");
        btnLaporBarang.setToolTipText("");
        btnLaporBarang.setFocusable(false);
        btnLaporBarang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLaporBarang.setMaximumSize(new java.awt.Dimension(177, 39));
        btnLaporBarang.setMinimumSize(new java.awt.Dimension(177, 39));
        btnLaporBarang.setPreferredSize(new java.awt.Dimension(177, 39));
        btnLaporBarang.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/hover.png"))); // NOI18N
        btnLaporBarang.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/active.png"))); // NOI18N
        btnLaporBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporBarangActionPerformed(evt);
            }
        });
        Sidebar.add(btnLaporBarang);

        btnStok.setBackground(new java.awt.Color(0, 0, 0));
        btnStok.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnStok.setForeground(new java.awt.Color(255, 255, 255));
        btnStok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default.png"))); // NOI18N
        btnStok.setText("Stok");
        btnStok.setToolTipText("");
        btnStok.setFocusable(false);
        btnStok.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStok.setMaximumSize(new java.awt.Dimension(177, 39));
        btnStok.setMinimumSize(new java.awt.Dimension(177, 39));
        btnStok.setPreferredSize(new java.awt.Dimension(177, 39));
        btnStok.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/hover.png"))); // NOI18N
        btnStok.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/active.png"))); // NOI18N
        btnStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStokActionPerformed(evt);
            }
        });
        Sidebar.add(btnStok);

        btnKaryawan.setBackground(new java.awt.Color(0, 0, 0));
        btnKaryawan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        btnKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default.png"))); // NOI18N
        btnKaryawan.setText("Karyawan");
        btnKaryawan.setToolTipText("");
        btnKaryawan.setFocusable(false);
        btnKaryawan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKaryawan.setMaximumSize(new java.awt.Dimension(177, 39));
        btnKaryawan.setMinimumSize(new java.awt.Dimension(177, 39));
        btnKaryawan.setPreferredSize(new java.awt.Dimension(177, 39));
        btnKaryawan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/hover.png"))); // NOI18N
        btnKaryawan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/active.png"))); // NOI18N
        btnKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaryawanActionPerformed(evt);
            }
        });
        Sidebar.add(btnKaryawan);

        btnSuplier.setBackground(new java.awt.Color(0, 0, 0));
        btnSuplier.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnSuplier.setForeground(new java.awt.Color(255, 255, 255));
        btnSuplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default.png"))); // NOI18N
        btnSuplier.setText("Suplier");
        btnSuplier.setToolTipText("");
        btnSuplier.setFocusable(false);
        btnSuplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSuplier.setMaximumSize(new java.awt.Dimension(177, 39));
        btnSuplier.setMinimumSize(new java.awt.Dimension(177, 39));
        btnSuplier.setPreferredSize(new java.awt.Dimension(177, 39));
        btnSuplier.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/hover.png"))); // NOI18N
        btnSuplier.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/active.png"))); // NOI18N
        btnSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuplierActionPerformed(evt);
            }
        });
        Sidebar.add(btnSuplier);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 250));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        Sidebar.add(jPanel1);

        btnLogout.setBackground(new java.awt.Color(123, 31, 31));
        btnLogout.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setToolTipText("");
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setMaximumSize(new java.awt.Dimension(177, 39));
        btnLogout.setMinimumSize(new java.awt.Dimension(177, 39));
        btnLogout.setPreferredSize(new java.awt.Dimension(177, 39));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        Sidebar.add(btnLogout);

        jSplitPane1.setLeftComponent(Sidebar);

        panelPages.setBackground(new java.awt.Color(0, 153, 153));
        panelPages.setPreferredSize(new java.awt.Dimension(765, 684));
        panelPages.setLayout(new java.awt.CardLayout());

        tambahBarangPage.setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Tambah Barang");

        header.setLayer(title, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        labelKodeBarang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelKodeBarang.setForeground(new java.awt.Color(51, 51, 51));
        labelKodeBarang.setText("Kode barang: ");

        inputNBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNBarangActionPerformed(evt);
            }
        });

        labelNamaBarang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNamaBarang.setForeground(new java.awt.Color(51, 51, 51));
        labelNamaBarang.setText("Nama barang: ");

        labelSuplier.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelSuplier.setForeground(new java.awt.Color(51, 51, 51));
        labelSuplier.setText("Suplier :");

        labelJumlah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelJumlah.setForeground(new java.awt.Color(51, 51, 51));
        labelJumlah.setText("Jumlah :");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Tambah Data Barang");

        btnSimpan.setBackground(new java.awt.Color(22, 103, 15));
        btnSimpan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        labelKodeBarangEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelKodeBarangEdit.setForeground(new java.awt.Color(51, 51, 51));
        labelKodeBarangEdit.setText("Kode barang: ");

        labelNamaBarangEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNamaBarangEdit.setForeground(new java.awt.Color(51, 51, 51));
        labelNamaBarangEdit.setText("Nama barang: ");

        labelSuplierEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelSuplierEdit.setForeground(new java.awt.Color(51, 51, 51));
        labelSuplierEdit.setText("Suplier :");

        labelJumlahEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelJumlahEdit.setForeground(new java.awt.Color(51, 51, 51));
        labelJumlahEdit.setText("Jumlah :");

        btnTambah.setBackground(new java.awt.Color(22, 103, 15));
        btnTambah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");

        cbKdBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbNmBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbSuplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout tambahBarangPageLayout = new javax.swing.GroupLayout(tambahBarangPage);
        tambahBarangPage.setLayout(tambahBarangPageLayout);
        tambahBarangPageLayout.setHorizontalGroup(
            tambahBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header)
            .addGroup(tambahBarangPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahBarangPageLayout.createSequentialGroup()
                        .addGroup(tambahBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(tambahBarangPageLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahBarangPageLayout.createSequentialGroup()
                        .addGroup(tambahBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tambahBarangPageLayout.createSequentialGroup()
                                .addGroup(tambahBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelNamaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(labelKodeBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelSuplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tambahBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputKBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputNBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnTambah))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tambahBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelNamaBarangEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelKodeBarangEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelSuplierEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelJumlahEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tambahBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputJumlahEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(cbKdBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbNmBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbSuplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(86, 86, 86))))
        );
        tambahBarangPageLayout.setVerticalGroup(
            tambahBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangPageLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGroup(tambahBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahBarangPageLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(tambahBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(labelKodeBarang)
                            .addComponent(inputKBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tambahBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(labelNamaBarang)
                            .addComponent(inputNBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tambahBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(labelSuplier)
                            .addComponent(inputSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tambahBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(labelJumlah)
                            .addComponent(inputJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tambahBarangPageLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(tambahBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(cbKdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelKodeBarangEdit))
                        .addGap(18, 18, 18)
                        .addGroup(tambahBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNamaBarangEdit)
                            .addComponent(cbNmBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tambahBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSuplierEdit)
                            .addComponent(cbSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tambahBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(labelJumlahEdit)
                            .addComponent(inputJumlahEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(tambahBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan)
                    .addComponent(btnTambah))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 117, Short.MAX_VALUE))
        );

        panelPages.add(tambahBarangPage, "tambahBarangPage");
        tambahBarangPage.getAccessibleContext().setAccessibleName("");

        laporBarangPage.setBackground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout laporBarangPageLayout = new javax.swing.GroupLayout(laporBarangPage);
        laporBarangPage.setLayout(laporBarangPageLayout);
        laporBarangPageLayout.setHorizontalGroup(
            laporBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        laporBarangPageLayout.setVerticalGroup(
            laporBarangPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );

        panelPages.add(laporBarangPage, "laporBarangPage");

        stokPage.setBackground(new java.awt.Color(255, 255, 255));

        title2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        title2.setForeground(new java.awt.Color(255, 255, 255));
        title2.setText("Stok Barang");

        header2.setLayer(title2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout header2Layout = new javax.swing.GroupLayout(header2);
        header2.setLayout(header2Layout);
        header2Layout.setHorizontalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        header2Layout.setVerticalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        btnSimpan2.setBackground(new java.awt.Color(22, 103, 15));
        btnSimpan2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnSimpan2.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan2.setText("Cari");
        btnSimpan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stokPageLayout = new javax.swing.GroupLayout(stokPage);
        stokPage.setLayout(stokPageLayout);
        stokPageLayout.setHorizontalGroup(
            stokPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stokPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stokPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(stokPageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(inputJumlahEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpan2))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        stokPageLayout.setVerticalGroup(
            stokPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stokPageLayout.createSequentialGroup()
                .addComponent(header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(stokPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSimpan2)
                    .addComponent(inputJumlahEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 326, Short.MAX_VALUE))
        );

        panelPages.add(stokPage, "stokPage");

        karyawanPage.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout karyawanPageLayout = new javax.swing.GroupLayout(karyawanPage);
        karyawanPage.setLayout(karyawanPageLayout);
        karyawanPageLayout.setHorizontalGroup(
            karyawanPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        karyawanPageLayout.setVerticalGroup(
            karyawanPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );

        panelPages.add(karyawanPage, "karyawanPage");

        suplierPage.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout suplierPageLayout = new javax.swing.GroupLayout(suplierPage);
        suplierPage.setLayout(suplierPageLayout);
        suplierPageLayout.setHorizontalGroup(
            suplierPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        suplierPageLayout.setVerticalGroup(
            suplierPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );

        panelPages.add(suplierPage, "suplierPage");

        jSplitPane1.setRightComponent(panelPages);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBarangActionPerformed
        cardLayout.show(panelPages, "tambahBarangPage");
    }//GEN-LAST:event_btnTambahBarangActionPerformed

    private void btnLaporBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporBarangActionPerformed
        cardLayout.show(panelPages, "laporBarangPage");
    }//GEN-LAST:event_btnLaporBarangActionPerformed

    private void btnStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStokActionPerformed
        cardLayout.show(panelPages, "stokPage"); 
    }//GEN-LAST:event_btnStokActionPerformed

    private void btnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaryawanActionPerformed
        cardLayout.show(panelPages, "karyawanPage");
    }//GEN-LAST:event_btnKaryawanActionPerformed

    private void btnLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoActionPerformed
        cardLayout.show(panelPages, "tambahBarangPage");
    }//GEN-LAST:event_btnLogoActionPerformed

    private void inputNBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNBarangActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSimpan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpan2ActionPerformed

    private void btnSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Sidebar;
    private javax.swing.JButton btnKaryawan;
    private javax.swing.JButton btnLaporBarang;
    private javax.swing.JButton btnLogo;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnSimpan2;
    private javax.swing.JButton btnStok;
    private javax.swing.JButton btnSuplier;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambahBarang;
    private javax.swing.JComboBox<String> cbKdBarang;
    private javax.swing.JComboBox<String> cbNmBarang;
    private javax.swing.JComboBox<String> cbSuplier;
    private javax.swing.JDesktopPane header;
    private javax.swing.JDesktopPane header2;
    private javax.swing.JTextField inputJumlah;
    private javax.swing.JTextField inputJumlahEdit;
    private javax.swing.JTextField inputJumlahEdit2;
    private javax.swing.JTextField inputKBarang;
    private javax.swing.JTextField inputNBarang;
    private javax.swing.JTextField inputSuplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JPanel karyawanPage;
    private javax.swing.JLabel labelJumlah;
    private javax.swing.JLabel labelJumlahEdit;
    private javax.swing.JLabel labelKodeBarang;
    private javax.swing.JLabel labelKodeBarangEdit;
    private javax.swing.JLabel labelNamaBarang;
    private javax.swing.JLabel labelNamaBarangEdit;
    private javax.swing.JLabel labelSuplier;
    private javax.swing.JLabel labelSuplierEdit;
    private javax.swing.JPanel laporBarangPage;
    private javax.swing.JPanel panelPages;
    private javax.swing.JPanel stokPage;
    private javax.swing.JPanel suplierPage;
    private javax.swing.JPanel tambahBarangPage;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
